version: '2'

services:

  idp-simplesamlphp:
    container_name: idp-simplesamlphp
    image: venatorfox/simplesamlphp:1.15.0
    environment:
      - CONFIG_BASEURLPATH=https://demo-idp.nebraskacloud.org/simplesaml/
      - CONFIG_AUTHADMINPASSWORD={SSHA256}MjJSiMlkQLa+fqI+CmQ1x1oUJ7OGucYpznKxBBHpgfC+Oh+7B9vgGw==
      - CONFIG_SECRETSALT=exampleabcdefghijklmnopqrstuvwxy
      - CONFIG_TECHNICALCONTACT_NAME=Adam Zheng
      - CONFIG_TECHNICALCONTACT_EMAIL=adam.zheng@esu10.org
      - CONFIG_LANGUAGEDEFAULT=en
      - CONFIG_TIMEZONE=America/Chicago
      - CONFIG_SHOWERRORS=true
      - CONFIG_ERRORREPORTING=false
      - CONFIG_ADMINPROTECTINDEXPAGE=false
      - CONFIG_ADMINPROTECTMETADATA=false
      - CONFIG_DEBUG=FALSE
      - CONFIG_LOGGINGLEVEL=NOTICE
      - CONFIG_LOGGINGHANDLER=file
      - CONFIG_LOGFILE=simplesamlphp.log
      - CONFIG_ENABLESAML20IDP=true
      - CONFIG_SESSIONREMEMBERMEENABLE=false
      - CONFIG_SESSIONREMEMBERMECHECKED=false
      - CONFIG_SESSIONCOOKIESECURE=false
      - CONFIG_ENABLEHTTPPOST=false
      - CONFIG_THEMEUSE=nebraskacloudAuth:nebraskaCloud
      - CONFIG_STORETYPE=memcache
      - CONFIG_MEMCACHESTOREPREFIX=simplesamlphp
      - CONFIG_MEMCACHESTORESERVERS=    'memcache_store.servers' => array(\n        array(\n             array('hostname' => 'idpa01-memcached'),\n             array('hostname' => 'idpa02-memcached'),\n        ),\n        array(\n             array('hostname' => 'idpb01-memcached'),\n             array('hostname' => 'idpb02-memcached'),\n        ),
      - OPENLDAP_TLS_REQCERT=never
#     - WWW_INDEX=core/authenticate.php?as=nebraskacloud-auth
    volumes:
      - /opt/docker/volumes/idp-simplesamlphp/config/:/var/simplesamlphp/config/:Z
      - /opt/docker/volumes/idp-simplesamlphp/cert/:/var/simplesamlphp/cert/:Z
      - /opt/docker/volumes/idp-simplesamlphp/dictionaries/:/var/simplesamlphp/dictionaries/:Z
      - /opt/docker/volumes/idp-simplesamlphp/log/:/var/simplesamlphp/log/:Z
      - /opt/docker/volumes/idp-simplesamlphp/metadata/:/var/simplesamlphp/metadata/:Z
      - /opt/docker/volumes/idp-simplesamlphp/modules/:/var/simplesamlphp/modules/:Z
      - /opt/docker/volumes/idp-simplesamlphp/templates/:/var/simplesamlphp/templates/:Z
      - /opt/docker/volumes/idp-simplesamlphp/www/:/var/simplesamlphp/www/:Z
    restart: always

  idpa01-memcached:
    container_name: idpa01-memcached
    image: memcached
    restart: always

  idpa02-memcached:
    container_name: idpa02-memcached
    image: memcached
    restart: always

  idpb01-memcached:
    container_name: idpb01-memcached
    image: memcached
    restart: always

  idpb01-memcached:
    container_name: idpb01-memcached
    image: memcached
    restart: always

  idp-haproxy:
    container_name: idp-haproxy
    image: million12/haproxy:1.7.9
    depends_on:
      - idp-simplesamlphp
    links:
      - idp-simplesamlphp
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/docker/volumes/idp-haproxy:/etc/haproxy:Z
    restart: always
    cap_add:
      - NET_ADMIN
