version: '3.5'

services:

  demo-simplesamlphp01:
    container_name: demo-simplesamlphp01
    image: venatorfox/simplesamlphp:1.17.1
    environment:
      - CONFIG_BASEURLPATH=https://demo-idp.nebraskacloud.org/simplesaml/
      - CONFIG_AUTHADMINPASSWORD={SSHA256}MjJSiMlkQLa+fqI+CmQ1x1oUJ7OGucYpznKxBBHpgfC+Oh+7B9vgGw==
      - CONFIG_SECRETSALT=exampleabcdefghijklmnopqrstuvwxy
      - CONFIG_TECHNICALCONTACT_NAME=Adam Zheng
      - CONFIG_TECHNICALCONTACT_EMAIL=adam.zheng@esu10.org
      - CONFIG_LANGUAGEDEFAULT=en
      - CONFIG_TIMEZONE=America/Chicago
      - CONFIG_SHOWERRORS=true
      - CONFIG_ERRORREPORTING=true
      - CONFIG_ADMINPROTECTINDEXPAGE=false
      - CONFIG_ADMINPROTECTMETADATA=false
      - CONFIG_DEBUG=FALSE
      - CONFIG_LOGGINGLEVEL=NOTICE
      - CONFIG_LOGGINGHANDLER=file
      - CONFIG_LOGFILE=simplesamlphp.log
      - CONFIG_ENABLESAML20IDP=true
      - CONFIG_SESSIONREMEMBERMEENABLE=false
      - CONFIG_SESSIONREMEMBERMECHECKED=false
      - CONFIG_SESSIONCOOKIESECURE=false
      - CONFIG_ENABLEHTTPPOST=false
      - CONFIG_THEMEUSE=nebraskacloudAuth:nebraskaCloud
      - CONFIG_STORETYPE=memcache
      - CONFIG_MEMCACHESTOREPREFIX=simplesamlphp
      - CONFIG_MEMCACHESTORESERVERS=    'memcache_store.servers' => [\n        [\n             ['hostname' => 'demo-memcacheda01'],\n             ['hostname' => 'demo-memcacheda02'],\n        ],\n        [\n             ['hostname' => 'demo-memcachedb01'],\n             ['hostname' => 'demo-memcachedb02'],\n        ],
      - OPENLDAP_TLS_REQCERT=never
#     - WWW_INDEX=core/authenticate.php?as=nebraskacloud-auth
      - OPENLDAP_TLS_REQCERT=always
      - MTA_NULLCLIENT=true
      - POSTFIX_MYHOSTNAME=demo-idp.nebraskacloud.org
      - POSTFIX_MYORIGIN=$$mydomain
      - POSTFIX_RELAYHOST=$$mydomain
      - POSTFIX_INETINTERFACES=loopback-only
      - POSTFIX_MYDESTINATION=
    volumes:
      - /srv/docker/volumes/demo-simplesamlphp01/config/:/var/simplesamlphp/config/:Z
      - /srv/docker/volumes/demo-simplesamlphp01/cert/:/var/simplesamlphp/cert/:Z
      - /srv/docker/volumes/demo-simplesamlphp01/locales/:/var/simplesamlphp/locales/:Z
      - /srv/docker/volumes/demo-simplesamlphp01/log/:/var/simplesamlphp/log/:Z
      - /srv/docker/volumes/demo-simplesamlphp01/metadata/:/var/simplesamlphp/metadata/:Z
      - /srv/docker/volumes/demo-simplesamlphp01/modules/:/var/simplesamlphp/modules/:Z
      - /srv/docker/volumes/demo-simplesamlphp01/templates/:/var/simplesamlphp/templates/:Z
      - /srv/docker/volumes/demo-simplesamlphp01/www/:/var/simplesamlphp/www/:Z
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.31.10

  demo-memcacheda01:
    container_name: demo-memcacheda01
    image: memcached:latest
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.31.20

  demo-memcacheda02:
    container_name: demo-memcacheda02
    image: memcached:latest
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.31.21

  demo-memcachedb01:
    container_name: demo-memcachedb01
    image: memcached:latest
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.31.30

  demo-memcachedb02:
    container_name: demo-memcachedb02
    image: memcached:latest
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.31.31

  demo-haproxy:
    container_name: demo-haproxy
    image: million12/haproxy:latest
    depends_on:
      - demo-simplesamlphp01
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/docker/volumes/demo-haproxy:/etc/haproxy/:Z
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 172.20.31.40

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.31.0/26
